version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data

volumes:
  postgres_dev: